CREATE TABLE IF NOT EXISTS tb_departamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tb_funcionario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    departamento_id BIGINT NOT NULL,
    salario DECIMAL(12, 2),
    CONSTRAINT fk_funcionario_departamento
        FOREIGN KEY (departamento_id) REFERENCES tb_departamento(id)
);

INSERT INTO tb_departamento (nome) VALUES ('TI');
INSERT INTO tb_departamento (nome) VALUES ('Administrativo');
INSERT INTO tb_departamento (nome) VALUES ('Financeiro');
INSERT INTO tb_departamento (nome) VALUES ('Marketing');

INSERT INTO tb_funcionario (nome, departamento_id, salario)
SELECT 'Lucas Silva', id, 5500.00 FROM tb_departamento WHERE nome = 'TI';
INSERT INTO tb_funcionario (nome, departamento_id, salario)
SELECT 'Mariana Costa', id, 4200.00 FROM tb_departamento WHERE nome = 'Administrativo';
INSERT INTO tb_funcionario (nome, departamento_id, salario)
SELECT 'Rafael Oliveira', id, 6100.00 FROM tb_departamento WHERE nome = 'Financeiro';
